weather_app/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.weather, name='weather'),
]

weather_app/weather_app/urls.py
from django.urls import path, include

urlpatterns = [
    path('weather/', include('weather.urls')),
]

weather_app/weather/models.py
from django.db import models

# Create your models here.

weather_app/weather/views.py
import os
from django.shortcuts import render
from .services import get_weather


def weather(request):
    city = request.GET.get('city', 'London') #hardcoded for now
    api_key = os.environ.get('OPENWEATHERMAP_API_KEY')

    weather_data = get_weather(city, api_key)
    print('goku', weather_data)
    context = {'weather': weather_data, 'city_name': city}
    return render(request, 'weather/weather.html', context)

weather_app/templates/weather/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Weather App</title>
</head>

<body>
    <h1>Weather in {{ city_name }}</h1>
    {% if weather %}
    <p>City: {{ weather.city }}</p>
    <p>Temperature: {{ weather.temperature }}°C</p>
    <p>Description: {{ weather.description }}</p>
    <img src="http://openweathermap.org/img/wn/{{ weather.icon }}.png" alt="Weather Icon">
    {% else %}
    <p>Weather data not available for this city.</p>
    {% endif %}
    <form method="GET" action="{% url 'weather:weather' %}">
        <input type="text" name="city" placeholder="Enter city">
        <button type="submit">Get Weather</button>
    </form>
</body>

</html>